image: python:latest    

stages:                 
  - build

read_secrets:
  stage: build
  image: hashicorp/vault:latest
  id_tokens:
    VAULT_AUTH_TOKEN:
      aud: $VAULT_AUTH_TOKEN
  script:
    - export VAULT_SKIP_VERIFY=1
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=$VAULT_AUTH_ROLE jwt=$VAULT_AUTH_TOKEN)"
    - echo $VAULT_TOKEN > .vault_token
  cache:  # Cache token
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .vault_token


run_automation:
  stage: build
  needs:
    - read_secrets
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .vault_token
  script:
    - apt install -y wkhtmltopdf
    - cp $rulesyaml  rules.yaml
    - cat rules.yaml
    - cat /etc/ssl/certs/ca-certificates.crt $ziro_ca > ca_bundle.crt
    - export REQUESTS_CA_BUNDLE=ca_bundle.crt
    - export VAULT_SKIP_VERIFY=1
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_TOKEN=$(cat .vault_token)
    - pip3 install -r requirements.txt
    - python3 mailreader.py --mailbox it-automation@goziro.com --vault prod/azure/it-automation
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
  
