image: python:latest    

stages:                 
  - build

read_secrets:
  stage: build
  image: hashicorp/vault:latest
  id_tokens:
    VAULT_AUTH_TOKEN:
      aud: $VAULT_AUTH_TOKEN
  script:
    - export VAULT_SKIP_VERIFY=1
    - export VAULT_ADDR=$VAULT_SERVER_URL
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=$VAULT_AUTH_ROLE jwt=$VAULT_AUTH_TOKEN)"
    - echo $VAULT_TOKEN > .vault_token
    - cp $rulesyaml  rules.yaml
    - cat rules.yaml

run_automation:
  stage: build
  needs:
    - read_secrets
  script:
    - export VAULT_TOKEN=$(cat .vault_token)
    - pip install -r requirements.txt
    - python3 mailreader.py --mailbox it-automation@goziro.com --vault prod/azure/it-automation
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
  
